export const strings = {
  title: 'Welcome to In-lib: Your Music Instruments Catalogues',
  welcome: 'Welcome to InLib!',
  description:
    'Explore IN-LIB, your go-to catalog for musical instruments from around the world. Start your musical journey with IN-LIB today.',
  addInstrument: 'Add New Instrument',
  search: 'Search',
  clearFilters: 'Clear filters',
  edit: 'Edit',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  signOut: 'Sign Out',
  save: 'Save',
  imgUpload: 'Upload image',
  uploadInfo: 'Upload PNG or JPG picture, 500x500 max with removed background',
  notHaveAccount: 'Don’t have an account?',
  doHaveAccount: 'Already have an account?',
  email: 'Email',
  password: 'Password',
  currentlyLogedIn: 'You are logged in as',
  confirmDelete: 'Are you sure you want to delete this instrument?',
  deleteSuccess: 'Instrument deleted successfully!',
  yesDelete: 'Yes, delete',
  cancelDelete: 'No, cancel',
  all: 'All',
  createdBy: 'Created by',
  placehilderImg: 'Placeholder image',
  uploadRules: 'Upload PNG or JPG picture, 500x500 max with removed background',
  delete: 'Delete',
  nothingFound: 'Sorry, nothing found',
  return: 'Return to the main page',
  errors: {
    userNotFound: 'No user found',
    userNotAuth: 'User not authenticated',
    fetchingError: 'Error fetching data:',
    errorDelete: 'Error deleting data:',
    formatError: 'Please upload a JPEG or PNG image.',
    uploadError: 'Error uploading image:',
    saveError: 'Failed to save instrument data.',
    updateError: 'Error updating',
    fethingData: 'Error fetching data',
  },
  status: {
    saveSuccess: 'Instrument data saved successfully!',
    deleteSuccess: 'Instrument deleted successfully!',
    noImg: 'Please upload an image before saving.',
  },
};
export const USER_MESSAGES = {
  TITLE: 'Welcome to In-lib: Your Music Instruments Catalogues',
  WELCOME: 'Welcome to InLib!',
  DESCRIPTION: 'Welcome to In-lib: Your Music Instruments Catalogue',
  ADD_INSTRUMENT: 'Add New Instrument',
  SEARCH: 'Search',
  CLEAR_FILTERS: 'Clear filters',
  EDIT: 'Edit',
  SIGN_IN: 'Sign In',
  SIGN_UP: 'Sign Up',
  SIGN_OUT: 'Sign Out',
  SAVE: 'Save',
  IMG_UPLOAD: 'Upload image',
  UPLOAD_INFO: 'Upload PNG or JPG picture, 500x500 max with removed background',
  NOT_HAVE_ACCOUNT: 'Don’t have an account?',
  DO_HAVE_ACCOUNT: 'Already have an account?',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  CURRENTLY_LOGGED_IN: 'You are logged in as',
  CONFIRM_DELETE: 'Are you sure you want to delete this instrument?',
  YES_DELETE: 'Yes, delete',
  CANCEL_DELETE: 'No, cancel',
  ALL: 'All',
  CREATED_BY: 'Created by',
  PLACEHOLDER_IMG: 'Placeholder image',
  UPLOAD_RULES: 'Upload PNG or JPG picture, 500x500 max with removed background',
  DELETE: 'Delete',
  NOTHING_FOUND: 'Sorry, nothing found',
  RETURN: 'Return to the main page',
  NOT_AUTH: 'You are not logged in',
  FAVS: 'Your favorite instruments are here!',
  STATUS: {
    SAVE_SUCCESS: 'Instrument data saved successfully!',
    DELETE_SUCCESS: 'Instrument deleted successfully!',
    NO_IMG: 'Please upload an image before saving.',
  },
};

// Server messages
export const SERVER_MESSAGES = {
  ERRORS: {
    USER_NOT_FOUND: 'No user found',
    USER_NOT_AUTH: 'User not authenticated',
    FETCHING_ERROR: 'Error fetching data:',
    ERROR_DELETE: 'Error deleting data:',
    FORMAT_ERROR: 'Please upload a JPEG or PNG image.',
    UPLOAD_ERROR: 'Error uploading image:',
    SAVE_ERROR: 'Failed to save instrument data.',
    UPDATE_ERROR: 'Error updating',
    FETCHING_DATA: 'Error fetching data',
  },
};
