import { ConfirmationCheck } from './components';

export const USER_MESSAGES = {
  TITLE: 'Welcome to In-lib: Your Music Instruments Catalogues',
  WELCOME: 'Welcome to InLib!',
  DESCRIPTION: 'Welcome to In-lib: Your Music Instruments Catalogue',
  ADD_INSTRUMENT: 'Add New Instrument',
  SEARCH: 'Search',
  CLEAR_FILTERS: 'Clear filters',
  EDIT: 'Edit',
  SIGN_IN: 'Sign In',
  SIGN_UP: 'Sign Up',
  SIGN_OUT: 'Sign Out',
  SAVE: 'Save',
  IMG_UPLOAD: 'Upload image',
  UPLOAD_INFO: 'Upload PNG or JPG picture, 500x500 max with removed background',
  NOT_HAVE_ACCOUNT: 'Don’t have an account?',
  DO_HAVE_ACCOUNT: 'Already have an account?',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  CURRENTLY_LOGGED_IN: 'You are logged in as',
  CONFIRM_DELETE: 'Are you sure you want to delete this instrument?',
  YES_DELETE: 'Yes, delete',
  CANCEL_DELETE: 'No, cancel',
  ALL: 'All',
  CREATED_BY: 'Created by',
  PLACEHOLDER_IMG: 'Placeholder image',
  UPLOAD_RULES: 'Upload PNG or JPG picture, 500x500, white background',
  DELETE: 'Delete',
  NOTHING_FOUND: 'Sorry, nothing found',
  RETURN: 'Return to the main page',
  STAY: 'Stay here',
  NOT_AUTH: 'You are not logged in',
  FAVS: 'Your favorite instruments are here!',
  CONFIRMATION_CHECK:
    "Check your email. If you didn't get a confirmation letter, click here to resend",
  RESEND: 'Resend',
  LOGIN_TO_ADD_FAVS: 'You must be logged in to add favorites',
  CONFIRMATION_LABEL: 'Confirm data',
  CONFIRMATION_REQUEST: 'You must confirm before submitting.',
  RELOAD: 'Reload page',
  SWITCH_DARK: 'Switch to dark mode',
  SWITCH_LIGHT: 'Switch to light mode',
  NO_FAVS: 'No favorites added yet. Browse the collections and discover your favorites!',
  VALIDATION: {
    INVALID_EMAIL: 'Invalid email address',
    INVALID_DOMAIN: 'Invalid email domain',
    INVALID_PASSWORD: 'Password must be at least 6 characters long',
  },
  STATUS: {
    SAVE_SUCCESS: 'Instrument data saved successfully!',
    DELETE_SUCCESS: 'Instrument deleted successfully!',
    NO_IMG: 'Please upload an image before saving.',
  },
};

export const SERVER_MESSAGES = {
  ERRORS: {
    USER_NOT_FOUND: 'No user found',
    USER_NOT_AUTH: 'User not authenticated',
    FETCHING_ERROR: 'Error fetching data:',
    ERROR_DELETE: 'Error deleting data:',
    FORMAT_ERROR: 'Please upload a JPEG or PNG image.',
    UPLOAD_ERROR: 'Error uploading image:',
    SAVE_ERROR: 'Failed to save instrument data.',
    UPDATE_ERROR: 'Error updating',
    FETCHING_DATA: 'Error fetching data',
    ERROR: 'Something went wrong',
  },
};
